<div class="idk3">
<h3>Contacts Details</h3>

    <div class="idk4">
        <img class="images" alt="photo" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/002-phone-receiver.svg'); ?>"/>
        <div>
            <label>(995) 555 111 333</label>
            <p>(722) 333 444 555</p>
        </div>
    </div>

    <div class="idk4">
        <img class="images" alt="photo" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/024-email.svg'); ?>"/>
        <div>
            <label>vendor@gmail.com</label>
            <p>magento@gmail.com</p>
        </div>
    </div>

    <div class="idk4">
        <img class="images" alt="photo" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/003-skype-logo.svg'); ?>"/>
        <div>
            <label>changelagunge</label>
            <p>loadskypelagunge</p>
        </div>
    </div>

</div>


