<body>

<ul class="giorgi">

    <div class="idk1">
        <li>
            <img class="images" alt="photo" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/011-truck.svg'); ?>"/>
            <div class="idk2">
                <label class="label1">FREE DELIVERY</label>
                <label>on orders over 100$</label>
            </div>
        </li>
    </div>

    <div class="idk1">
        <li>
            <img class="images" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/003-gift.svg'); ?>"  alt="gift" />
            <div class="idk2">
                <label class="label1">CHOOSE A FREE GIFTS</label>
                <label>with every purchase</label>
            </div>
        </li>
    </div>

    <div class="idk1">
        <li>
            <img class="images" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/006-padlock.svg'); ?>"  alt="padlock" />
            <div class="idk2">
                <label class="label1">100% SECURE SHOPPING</label>
                <label>mauris ac pulvinar</label>
            </div>
        </li>
    </div>



</ul>

</body>


